# generated by datamodel-codegen:
#   filename:  buff_visuals.schema.json

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Optional[str] = None
    item: Optional[str] = None
    description: Optional[str] = None
    name: Optional[str] = None


class Sources(RootModel[Optional[Dict[str, List[Source]]]]):
    root: Optional[Dict[str, List[Source]]] = None


class BuffVisualsSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Optional[str] = None
    icon: Optional[str] = None
    name: Optional[str] = None
    sources: Optional[Sources] = None
    sounds: Optional[List[str]] = None
    custom_frame: Optional[str] = None


class Model(RootModel[Optional[Dict[str, BuffVisualsSchemaValue]]]):
    root: Optional[Dict[str, BuffVisualsSchemaValue]] = None
