# generated by datamodel-codegen:
#   filename:  characters.schema.json
#   timestamp: 2024-05-08T08:33:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class Unarmed(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attack_time: int
    max_physical_damage: int
    min_physical_damage: int
    range: int


class MetadataID(RootModel[str]):
    root: str


class BaseStats(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dexterity: int
    intelligence: int
    life: int
    mana: int
    strength: int
    unarmed: Unarmed


class CharactersSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_stats: BaseStats
    integer_id: int
    metadata_id: MetadataID
    name: str


class Model(RootModel[List[CharactersSchemaElement]]):
    root: List[CharactersSchemaElement]
