# generated by datamodel-codegen:
#   filename:  cluster_jewel_notables.schema.json
#   timestamp: 2024-05-08T08:33:01+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class ClusterJewelNotablesSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    jewel_stat: str
    name: str


class Model(RootModel[List[ClusterJewelNotablesSchemaElement]]):
    root: List[ClusterJewelNotablesSchemaElement]
