# generated by datamodel-codegen:
#   filename:  cost_types.schema.json
#   timestamp: 2024-05-08T03:19:22+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class CostTypesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    format_text: str
    stat: str


class Model(RootModel[Optional[Dict[str, CostTypesSchemaValue]]]):
    root: Optional[Dict[str, CostTypesSchemaValue]] = None
