# generated by datamodel-codegen:
#   filename:  mod_types.schema.json
#   timestamp: 2024-05-08T08:05:14+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class ModTypesSchemaValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sell_price_types: List[str]


class Model(RootModel[Optional[Dict[str, ModTypesSchemaValue]]]):
    root: Optional[Dict[str, ModTypesSchemaValue]] = None
