# generated by datamodel-codegen:
#   filename:  mods_by_base.schema.json
#   timestamp: 2024-05-08T06:07:46+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, RootModel


class ItemClasses1(BaseModel):
    pass


class GenerationTypes1(BaseModel):
    pass


class ModTypes1(BaseModel):
    pass


class ModWeights1(BaseModel):
    pass


class ModWeights(RootModel[Union[List[int], ModWeights1]]):
    root: Union[List[int], ModWeights1]


class ModTypes(RootModel[Union[List[ModWeights], ModTypes1]]):
    root: Union[List[ModWeights], ModTypes1]


class GenerationTypes(RootModel[Union[List[ModTypes], GenerationTypes1]]):
    root: Union[List[ModTypes], GenerationTypes1]


class Tags(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    bases: Optional[List[str]] = None
    mods: Optional[GenerationTypes] = None


class ItemClasses(RootModel[Union[List[Tags], ItemClasses1]]):
    root: Union[List[Tags], ItemClasses1]


class Model(RootModel[ItemClasses]):
    root: ItemClasses
