# generated by datamodel-codegen:
#   filename:  uniques_poewiki.schema.json
#   timestamp: 2024-05-08T10:03:30+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class UniquesPoewikiSchemaElement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    base_item: str
    base_item_id: Optional[str] = None
    cannot_be_traded_or_modified: bool
    description: Optional[str] = None
    drop_enabled: bool
    is_account_bound: bool
    is_corrupted: bool
    is_drop_restricted: bool
    is_eater_of_worlds_item: bool
    is_fractured: bool
    is_in_game: bool
    is_replica: bool
    is_searing_exarch_item: bool
    is_synthesised: bool
    is_unmodifiable: bool
    is_veiled: bool
    item_class: str
    item_class_id: str
    name: str
    name_list: str
    page_name: str
    release_version: Optional[str] = None
    required_dexterity: Optional[int] = None
    required_intelligence: Optional[int] = None
    required_level: int
    required_strength: Optional[int] = None
    tags: str
    drop_monsters: Optional[str] = None
    drop_text: Optional[str] = None
    drop_level: Optional[int] = None
    acquisition_tags: Optional[str] = None
    drop_areas: Optional[str] = None
    removal_version: Optional[str] = None
    influences: Optional[str] = None
    is_relic: Optional[bool] = None


class Model(RootModel[Optional[Dict[str, List[UniquesPoewikiSchemaElement]]]]):
    root: Optional[Dict[str, List[UniquesPoewikiSchemaElement]]] = None
