name: Check patch version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.2.0
      with:
        token: ${{ secrets.VERSION_COMMIT_PAT }}
    - name: get version
      run: curl https://raw.githubusercontent.com/poe-tool-dev/latest-patch-version/main/latest.txt > RePoE/version.txt
    - name: get schema hash
      run: git ls-remote https://github.com/poe-tool-dev/dat-schema.git refs/heads/main > RePoE/schema.txt
    - name: set version
      id: set-version
      run: echo "version=$(cat RePoE/version.txt)" >> "$GITHUB_OUTPUT"
    - name: commit changes
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: "Version ${{ steps.set-version.outputs.version }}"
