name: GitHub Actions Version Updater

on:
  workflow_dispatch:
  schedule:
    # Automatically run on every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: .github
          token: ${{ secrets.VERSION_COMMIT_PAT }}

      - run: rm .git/hooks/*

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.VERSION_COMMIT_PAT }}
